export const CLUBS = [
  ['Athletico-PR','CAP','Sul',74],['Atlético-MG','CAM','Sudeste',78],['Bahia','BAH','Nordeste',75],['Botafogo','BOT','Sudeste',77],['Chapecoense','CHA','Sul',68],['Corinthians','COR','Sudeste',76],['Coritiba','CFC','Sul',70],['Cruzeiro','CRU','Sudeste',79],['Flamengo','FLA','Sudeste',84],['Fluminense','FLU','Sudeste',78],['Grêmio','GRE','Sul',76],['Internacional','INT','Sul',77],['Mirassol','MIR','Sudeste',69],['Palmeiras','PAL','Sudeste',86],['Red Bull Bragantino','RBB','Sudeste',74],['Remo','REM','Norte',67],['Santos','SAN','Sudeste',75],['São Paulo','SAO','Sudeste',79],['Vasco','VAS','Sudeste',73],['Vitória','VIT','Nordeste',68]
].map(([name,short,region,strength],id)=>({id,name,short,region,strength,budget:Math.round(strength*120000)}));
const FIRST=['Rafael','Caio','Luan','Enzo','Matheus','João','Pedro','Arthur','Lucas','Gustavo','Murilo','Bernardo','Davi','Vitor','Heitor','Samuel','Nicolas','Gabriel','André','Yuri','Diego','Felipe'];
const LAST=['Almeida','Barbosa','Cardoso','Costa','Dias','Ferreira','Gomes','Lima','Mendes','Nogueira','Oliveira','Pereira','Ramos','Rocha','Santos','Silva','Souza','Teixeira','Vieira','Moura','Azevedo','Batista'];
const ROLES=['GK','DEF','DEF','DEF','DEF','MID','MID','MID','MID','MID','FWD','FWD','FWD','FWD','GK','DEF','MID','MID','FWD','FWD'];
export function makeSquad(club,seed=club.id){return ROLES.map((role,i)=>({id:`${club.short}-${i}`,name:`${FIRST[(i+seed)%FIRST.length]} ${LAST[(i*3+seed)%LAST.length]}`,role,rating:Math.max(55,Math.min(92,club.strength+((i*7+seed*3)%15)-7)),age:18+((i*5+seed)%17),morale:72,clubId:club.id}));}
export function priceFor(p){return Math.round((p.rating*9000)+(30-p.age)*1200);}
export function makeMarket(clubs){return clubs.flatMap(c=>makeSquad(c).map(p=>({...p,price:priceFor(p)})));}
export function makeFreeAgents(){const roles=['GK','DEF','MID','FWD'];return Array.from({length:60},(_,i)=>{const p={id:`FA-${i}`,name:`${FIRST[(i+5)%FIRST.length]} ${LAST[(i*5+2)%LAST.length]}`,role:roles[i%4],rating:58+(i%25),age:18+(i%18),morale:55+(i%35),clubId:null};return {...p,price:priceFor(p)};});}
