export function emptyTable(clubs){return Object.fromEntries(clubs.map(c=>[c.id,{clubId:c.id,played:0,wins:0,draws:0,losses:0,goalsFor:0,goalsAgainst:0,points:0}]))}
export function schedule(clubs,rng=Math.random){const list=clubs.map(c=>c.id),rounds=[];for(let r=0;r<clubs.length-1;r++){const games=[];for(let i=0;i<clubs.length/2;i++){let home=list[i],away=list[list.length-1-i];if(rng()>=.5)[home,away]=[away,home];games.push({round:r+1,home,away});}for(let i=games.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[games[i],games[j]]=[games[j],games[i]];}list.splice(1,0,list.pop());rounds.push(...games);}return rounds.concat(rounds.map(g=>({round:g.round+clubs.length-1,home:g.away,away:g.home})))}
export function formationBonus(formation){return {'4-3-3':2,'4-4-2':0,'3-5-2':1,'5-3-2':-1}[formation]??0;}
export function tacticStrength(base,tactic={}){const style={attacking:2,balanced:0,defensive:-1,possession:1}[tactic.style]??0;return base+formationBonus(tactic.formation)+style;}
export function chooseLineup(squad,tactic={}){const needs={'4-3-3':{GK:1,DEF:4,MID:3,FWD:3},'4-4-2':{GK:1,DEF:4,MID:4,FWD:2},'3-5-2':{GK:1,DEF:3,MID:5,FWD:2},'5-3-2':{GK:1,DEF:5,MID:3,FWD:2}}[tactic.formation]||{GK:1,DEF:4,MID:4,FWD:2};const score=p=>p.rating+(p.morale||0)*.15;const pool=[...squad],starters=[];for(const role of ['GK','DEF','MID','FWD']){const chosen=pool.filter(p=>p.role===role).sort((a,b)=>score(b)-score(a)).slice(0,needs[role]);starters.push(...chosen);chosen.forEach(p=>pool.splice(pool.indexOf(p),1));}while(starters.length<11){const best=pool.sort((a,b)=>score(b)-score(a)).shift();if(!best)break;starters.push(best);}return {starters,reserves:pool};}
export function teamStrength(state,clubId){const club=state.clubs[clubId],squad=state.clubSquads?.[clubId];if(!squad?.length)return club.strength;const tactic=state.tactics?.[clubId]||{formation:'4-4-2',style:'balanced'};const lineup=state.lineups?.[clubId]||chooseLineup(squad,tactic);const players=lineup.starters||lineup;const avgRating=players.reduce((n,p)=>n+p.rating,0)/players.length;const avgMorale=players.reduce((n,p)=>n+(p.morale||0),0)/players.length;return tacticStrength(avgRating,tactic)+(avgMorale-70)*.08;}
export function result(home,away,rng=Math.random,homeTactic={},awayTactic={}){const h=Math.max(.2,tacticStrength(home.strength,homeTactic)/75),a=Math.max(.2,tacticStrength(away.strength,awayTactic)/75);return [Math.min(5,Math.floor(rng()*2.4*h+rng()*1.3)),Math.min(5,Math.floor(rng()*2.1*a))];}
export function playMatch(state,homeId,awayId,rng=Math.random){const home=state.clubs[homeId],away=state.clubs[awayId];const homeEffective={...home,strength:teamStrength(state,homeId)},awayEffective={...away,strength:teamStrength(state,awayId)};const [hg,ag]=result(homeEffective,awayEffective,rng,state.tactics?.[homeId]||{},state.tactics?.[awayId]||{});const h=state.table[homeId],a=state.table[awayId];for(const t of [h,a])t.played++;h.goalsFor+=hg;h.goalsAgainst+=ag;a.goalsFor+=ag;a.goalsAgainst+=hg;if(hg>ag){h.wins++;h.points+=3;a.losses++;}else if(hg<ag){a.wins++;a.points+=3;h.losses++;}else{h.draws++;a.draws++;h.points++;a.points++;}return {home:home.name,away:away.name,hg,ag,homeId,awayId};}
export function playRound(state,round,rng=Math.random){const games=(state.schedule||schedule(Object.values(state.clubs),rng)).filter(g=>g.round===round);return games.map(g=>playMatch(state,g.home,g.away,rng));}
export function tableRows(state){return Object.values(state.table).sort((a,b)=>b.points-a.points||(b.goalsFor-b.goalsAgainst)-(a.goalsFor-a.goalsAgainst)||b.goalsFor-a.goalsFor).map((r,i)=>({...r,pos:i+1,club:state.clubs[r.clubId]}));}
